# 使用 Maven 镜像来构建应用
FROM maven:3.9.4-eclipse-temurin-21 AS build

# 设置工作目录
WORKDIR /app

# 复制父级 pom.xml 和子项目目录
# 复制父级 pom.xml 和子项目的 pom.xml
COPY ../pom.xml /app/         
COPY pom.xml /app/gateway/
COPY src /app/gateway/src/

# 构建应用
WORKDIR /app/gateway

# 使用 Maven 构建项目，生成 JAR 文件
RUN mvn clean install -DskipTests -Dparent

# 使用轻量级的 OpenJDK 镜像来运行应用
FROM eclipse-temurin:21-alpine

# 设置工作目录
WORKDIR /app

# 从 build 阶段复制构建好的 JAR 文件到当前容器
COPY --from=build /app/gateway/target/*.jar app.jar

# 暴露应用端口
EXPOSE 8080

# 运行 Spring Boot 应用
ENTRYPOINT ["java", "-jar", "app.jar"]