---
logging:
  level:
    org.springframework.cloud.consul: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: health
server:
  port: 8080
spring:
  application:
    name: gateway-service
  cloud:
    consul:
      config:
        enabled: true
        format: YAML
        profileSeparator: .
        watch:
          delay: 10000
          enabled: true
      discovery:
        enabled: true
        healthCheckInterval: 10s
        healthCheckPath: /actuator/health
        # ip-address: ${GATEWAY_HOST:192.168.10.7}
        prefer-ip-address: true
        register: true
        service-name: ${spring.application.name}
      host: localhost
      port: 8500
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - filters:
            - RewritePath=/serviceuser/(?<segment>.*), /${segment}
          id: service-user
          predicates:
            - Path=/serviceuser/users/**
          uri: lb://service-user
  config:
    # consul kv get config/gateway-service.dev/data
    import: optional:consul:localhost:8500
  profiles:
    active: dev