---
management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, prometheus
  metrics:
    export:
      prometheus:
        enabled: true
server:
  port: 8081
spring:
  application:
    name: service-user
  cache:
    type: redis
  cloud:
    consul:
      config:
        enabled: true
        format: YAML
        profileSeparator: .
        watch:
          delay: 10000
          enabled: true
      discovery:
        enabled: true
        healthCheckInterval: 10s
        healthCheckPath: /actuator/health
        register: true
        service-name: ${spring.application.name}
      host: localhost
      port: 8500
  config:
    import: consul:${spring.cloud.consul.host}:${spring.cloud.consul.port}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ${spring.datasource.password:}
    url: ${spring.datasource.url:jdbc:mysql://localhost:3306/springdemo?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true}
    username: ${spring.datasource.username:root}
  mybatis:
    configuration:
      map-underscore-to-camel-case: true
  profiles:
    active: dev
springdoc:
  api-docs:
    enabled: true
  info:
    description: 这是一个 Spring Boot + MyBatis 3 的用户服务 API 文档
    title: 用户服务 API
    version: 1.0.0
  swagger-ui:
    enabled: true
    path: /swagger-ui.html