---
server:
  port: 8081
spring:
  application:
    name: service-user
  cloud:
    consul:
      config:
        enabled: true
        format: YAML
        profileSeparator: .
        watch:
          delay: 10000
          enabled: true
      discovery:
        enabled: true
        healthCheckInterval: 10s
        healthCheckPath: /actuator/health
        # ip-address: ${GATEWAY_HOST:192.168.10.7}
        register: true
        service-name: ${spring.application.name}
      host: localhost
      port: 8500
  config:
    # consul kv get config/service-user.dev/data
    import: optional:consul:localhost:8500
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
    url: jdbc:mysql://localhost:3306/springdemo?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
  mybatis:
    configuration:
      map-underscore-to-camel-case: true
  profiles:
    active: dev
springdoc:
  api-docs:
    enabled: true
  info:
    description: 这是一个 Spring Boot + MyBatis 3 的用户服务 API 文档
    title: 用户服务 API
    version: 1.0.0
  swagger-ui:
    enabled: true
    path: /swagger-ui.html