# 使用轻量级的 OpenJDK 镜像来运行应用
FROM m.daocloud.io/docker.io/library/amazoncorretto:21.0.6-alpine3.21

# 设置工作目录
WORKDIR /app

# 从 build 阶段复制构建好的 JAR 文件到当前容器
COPY target/*.jar app.jar

# 暴露应用端口
EXPOSE 8081

# 运行 Spring Boot 应用
ENTRYPOINT ["java", "-jar", "app.jar"]